---
title: "Immune marker data"
author: "Christelle Colin-Leitzinger"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: cerulean #darkly
    highlight: pygments
    df_print: paged
---

<style type="text/css">
h1.title {
  font-size: 25px;
}
.figure {
   margin-top: 25px;
   <!-- margin-bottom: 100px; -->
}

table {
    margin-top: 25px;
    <!-- margin-bottom: 100px !important; -->
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      # fig.width = 7, fig.height = 5, 
                      fig.align='center'#, fig.show='hold'
                      )
options(gtsummary.print_engine = "gt")
options(gtsummary.as_gt.addl_cmds = "gt::tab_options(table.font.size = 14, data_row.padding = gt::px(1))")
```

<style>
div.blue { background-color:#0099CC; border-radius: 5px; padding: 20px; font-size: 38px}
</style>
<div class = "blue">

<span style="color: white;">Immune Marker Data</span>

</div>
<br>

```{r library, include=FALSE}
# library(drake)
library(tidyverse)
library(data.table)
# library(VennDiagram)
# library(gtsummary)
# library(survival)
# library(survminer)
library(psych)
# library(corrplot)
# library(ggcorrplot)
# library(mclust)
```

```{r load}
# loadd(clinical_data, ROI_tumor ,ROI_stroma ,ROI_total,
#       cases_match)

ROI_global <- readRDS("/Users/colinccm/Documents/GitHub/Peres/IF_AACES_NCOCS/ROI_global.rds")
clinical_data <- readRDS("/Users/colinccm/Documents/GitHub/Peres/IF_AACES_NCOCS/clinical_data.rds")

# Rewove patients not matched or lost match
ROI_global <- left_join(ROI_global, clinical_data, by="suid") %>% drop_na(pair_id) %>% 
  group_by(pair_id) %>% 
  mutate(have_a_match = dense_rank(interaction(suid, pair_id))) %>% 
  group_by(pair_id) %>% 
  mutate(is_paired = max(have_a_match)) %>% 
  filter(is_paired == 2) %>% 
  select(pair_id, everything(), -c(is_paired, have_a_match)) %>% 
  ungroup()

# markers_match <- readRDS("/Users/colinccm/Documents/GitHub/Peres/IF_AACES_NCOCS/markers_match.rds")
path <- fs::path("","Volumes","Peres_Research","Christelle Colin-Leitzinger", "IF_AACES_NCOCS", "Figures")



```
<br>
<br>

***

# I. ROIs Raw Data
## 1. Cells Distribution
```{r}
p1 <- ROI_global %>% 
  filter(intratumoral_i_vs_peripheral_p_ == "Intratumoral") %>% 
  mutate(Tumor = "Tumor") %>% 
  mutate(Stroma = "Stroma") %>% 
  ggplot()+
  geom_violin(aes(x=Tumor, y=percent_tumor), scale = "count")+
  geom_boxplot(aes(x=Tumor, y=percent_tumor), width=.1) +
  geom_violin(aes(x=Stroma, y=percent_stroma), scale = "count") +
  geom_boxplot(aes(x=Stroma, y=percent_stroma), width=.1) +
  labs(x="Cell type", y=NULL, title="Intratumoral \nROIs")
p2 <- ROI_global %>% 
  filter(intratumoral_i_vs_peripheral_p_ == "Peripheral") %>% 
  mutate(Tumor = "Tumor") %>% 
  mutate(Stroma = "Stroma") %>% 
  ggplot()+
  geom_violin(aes(x=Tumor, y=percent_tumor), scale = "count")+
  geom_boxplot(aes(x=Tumor, y=percent_tumor), width=.1) +
  geom_violin(aes(x=Stroma, y=percent_stroma), scale = "count") +
  geom_boxplot(aes(x=Stroma, y=percent_stroma), width=.1) +
  labs(x="Cell type", y=NULL, title="Peripheral \nROIs")

# tiff(paste0(path, "/violin plot distribution tumor and stroma cells in ROIs intra-periph.tiff"))
gridExtra::grid.arrange(p1, p2, ncol = 2, 
                        top = "% of Cells Present in", left = "% Cells per samples", 
                        bottom = "Data on Race-Matched Patients")
# dev.off()
```

## 2. ICC
```{r}
ICC_roi_periph <- ROI_global %>%
  filter(intratumoral_i_vs_peripheral_p_ == "Peripheral") %>% 
  select(suid, image_tag, #tumor_total_cells, stroma_total_cells, 
         contains("percent"))
class(ICC_roi_periph) <- "data.frame"
ICC_data <- data.frame(matrix(nrow=1, ncol=0))

for(i in 1:length(colnames(ICC_roi_periph))) {
  
  rad <- ICC_roi_periph %>% select(suid)
  
  if(class(ICC_roi_periph[,i]) == "numeric" | class(ICC_roi_periph[,i]) == "integer") {
    
    ICC_df <- cbind(rad, value = ICC_roi_periph[,i])
    ICC_df <- ICC_df %>%
      mutate(Slide = "Slide0") %>%
      group_by(suid) %>%
      mutate(n = row_number(suid)) %>%
      ungroup() %>%
      unite(slide_id, Slide:n, sep = "", remove = TRUE, na.rm = TRUE) %>%
      pivot_wider(names_from = slide_id, values_from = value) %>%
      select(c(starts_with("slide")))
    
    ICC <- ICC(ICC_df)$results[4,2]
    ICC_data <- cbind(ICC_data,ICC)
    
  }
  
}
colnames(ICC_data) <- colnames(ICC_roi_periph)[3:ncol(ICC_roi_periph)]

rm(ICC_df, ICC, i,  rad)
```

## New ICC function
```{r}
new_icc <- function(ROI_global) {
  icc_overall <- ROI_global %>%
    select(suid, image_tag,
           contains("percent"))
  class(icc_overall) <- "data.frame"
  
  icc_intrat <- ROI_global %>%
    filter(intratumoral_i_vs_peripheral_p_ == "Peripheral") %>%
    select(suid, image_tag,
           contains("percent"))
  class(icc_intrat) <- "data.frame"
  
  icc_periph <- ROI_global %>%
    filter(intratumoral_i_vs_peripheral_p_ == "Peripheral") %>%
    select(suid, image_tag,
           contains("percent"))
  class(icc_periph) <- "data.frame"
  
  fct_icc <- function(data) {
    ICC_data <- data.frame(matrix(nrow = 1, ncol = 0))
    lb_data <- data.frame(matrix(nrow = 1, ncol = 0))
    up_data <- data.frame(matrix(nrow = 1, ncol = 0))
    for (i in 1:length(colnames(data))) {
      rad <- data %>% select(suid)
      
      if (class(data[, i]) == "numeric" |
          class(data[, i]) == "integer") {
        ICC_df <- cbind(rad, value = data[, i])
        ICC_df <- ICC_df %>%
          mutate(Slide = "Slide0") %>%
          group_by(suid) %>%
          mutate(n = row_number(suid)) %>%
          ungroup() %>%
          unite(slide_id, Slide:n, sep = "", remove = TRUE, na.rm = TRUE) %>%
          pivot_wider(names_from = slide_id, values_from = value) %>%
          select(c(starts_with("slide")))
        
        ICC <- ICC(ICC_df)$results[4, 2]
        ICC_data <- cbind(ICC_data, ICC)
        ICC <- ICC(ICC_df)$results[4, 7]
        lb_data <- cbind(lb_data, ICC)
        ICC <- ICC(ICC_df)$results[4, 8]
        up_data <- cbind(up_data, ICC)
        
      }
      
    }
    ICCC_data <- bind_rows(ICC_data, lb_data, up_data)
    colnames(ICCC_data) <- colnames(data)[3:ncol(data)]
    ICCC_data <- as.data.frame(t(ICCC_data)) %>%
      mutate(ICC_lb_up = paste(round(V1, 2), " (", round(V2, 2), ", ", round(V3, 2), ")", sep = "")) %>%
      select(ICC_lb_up)
  }
  
  icc_overall <-
    fct_icc(icc_overall) %>% rename(Overall = "ICC_lb_up")
  icc_intrat <-
    fct_icc(icc_intrat) %>% rename(Intratumoral = "ICC_lb_up")
  icc_periph <-
    fct_icc(icc_periph) %>% rename(Peripheral = "ICC_lb_up")
  
  icc_data <- cbind(icc_overall, icc_intrat, icc_periph)
  
}

b <- new_icc(ROI_global)
b
```
<br>
<br>

***

# II. Abundance



