---
title: "Response to reviewer"
author: "Christelle Colin-Leitzinger"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: cerulean #darkly
    highlight: pygments
    df_print: paged
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
h1.title {
  font-size: 25px;
}
.figure {
   margin-top: 25px;
   <!-- margin-bottom: 100px; -->
}

table {
    margin-top: 25px;
    <!-- margin-bottom: 100px !important; -->
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      # fig.width = 7, fig.height = 5, 
                      fig.align='center'#, fig.show='hold'
                      )
options(gtsummary.print_engine = "gt")
options(gtsummary.as_gt.addl_cmds = "gt::tab_options(table.font.size = 14, data_row.padding = gt::px(1))")
```

<br>

```{r library, include=FALSE}
# library(drake)
library(tidyverse)
library(data.table)
# library(VennDiagram)
library(gtsummary)
library(survival)
library(survminer)
library(psych)
# library(corrplot)
# library(ggcorrplot)
library(mclust)
library(sensemakr)
library(gplots)
library(ggridges)
library(ComplexHeatmap)
```

```{r load}
# loadd(clinical_data, ROI_tumor ,ROI_stroma ,ROI_total,
#       cases_match)

# Remove these IDs from whole data because 2 are NAs in BMI and 2 are there matched
# remove_id_bmi <- paste0(c("45142", "45809", "181810", "42204"), collapse = "|")

ROI_global <- readRDS("/Users/colinccm/Documents/GitHub/Peres/IF_AACES_NCOCS/ROI_global.rds")
clinical_data <- readRDS("/Users/colinccm/Documents/GitHub/Peres/IF_AACES_NCOCS/clinical_data.rds")

# Rewove patients not matched or lost match
ROI_global <- left_join(ROI_global, clinical_data, by="suid") %>%
  filter(!image_tag %in% c("Peres_P1_150163  3D_[44113,18531].tif", 
                           "Peres_P1_43004 A2_[45654,5840].tif",
                           "Peres_P1_43773 D2_[60849,15244].tif", 
                         "Peres_P1_AACES 130033_[37754,17929].tif",
                         "Peres_P1_AACES 130033_[38351,13944].tif"
                           )) %>% 
  select(suid, pair_id, everything()) %>% 
  drop_na(pair_id) %>% 
  group_by(pair_id) %>% 
  mutate(have_a_match = dense_rank(interaction(suid, pair_id))) %>% 
  group_by(pair_id) %>% 
  mutate(is_paired = max(have_a_match)) %>% 
  filter(is_paired == 2) %>% 
  select(pair_id, everything(), -c(is_paired, have_a_match)) %>% 
  ungroup()

# markers_match <- readRDS("/Users/colinccm/Documents/GitHub/Peres/IF_AACES_NCOCS/markers_match.rds")
path <- fs::path("","Volumes","Peres_Research","Christelle Colin-Leitzinger", "IF_AACES_NCOCS", "Disparities manuscript", "Figures")

# Remove these IDs from peripheral ROI because 2 are NAs and 2 are there matched
remove_id <- paste0(c("110318", "43220", "42774", "46619"), collapse = "|")
```


```{r}
ROI_i <- ROI_global %>% 
  filter(intratumoral_i_vs_peripheral_p_ == "Intratumoral")
ROI_p <- ROI_global %>% 
  filter(intratumoral_i_vs_peripheral_p_ == "Peripheral")
```
<br>

***

# RESPONSE excluded

```{r}
paired <- clinical_data %>% 
  filter(str_detect(suid, "43131|43229|46610|47071|47226|47372|48091|48110|120142")) %>% 
  select(pair_id)
paired <- paste0(paired$pair_id, collapse = "|")

excluded <- clinical_data %>% 
  filter(str_detect(pair_id, paired))

bind_rows(ROI_global %>%
            distinct(suid, .keep_all = TRUE) %>% 
            mutate(excluded = "included"),
          excluded %>% 
            mutate(excluded = "excluded")) %>% 
  select(refage, refage_cat, stage, BMI_recent, BMI_recent_grp,
        smoker, diab,
         dblkstat_CA125, adj, excluded, site) %>% 
  tbl_summary(by = excluded,
              statistic = list(all_continuous() ~ "{mean} ({sd})"),
              label = list(refage ~ "Age at diagnosis", refage_cat ~ "Age at diagnosis category",
                           dblkstat_CA125 ~ "Debulking Status", adj ~ "Adjuvant chemotherapy",
                           smoker ~ "Smoking status"),
              type = list(diab ~ "categorical"),
              digits = list(all_continuous() ~ 1)) %>%
      modify_header(list(label ~ "**Patient characteristics**", all_stat_cols() ~ "**{level}**, N = {n}")) %>% 
  add_overall() %>% bold_labels() %>% add_p() %>% bold_p(t = .05)
```

***

# RESPONSE survival curve by race for this dataset
```{r}
clin_surv <- ROI_global %>% 
  distinct(suid, .keep_all = TRUE)
mysurv <- Surv(time = clin_surv$timeint_fu, event = clin_surv$surv_vital)
myplot <- survfit(mysurv~clin_surv$race)

# pdf(paste0(path, "/Survivals/Immune cell clusters/OS CD3 grp matched pop.pdf"), width = 8, height = 7)
myplot <- ggsurvplot(myplot, data = clin_surv,
           title = "Survival analysis on matched population", #subtitle = "Grouping based on intratumoral overall CD3+ cells",
           font.main = c(14, "bold", "black"), font.subtitle = c(6, "plain", "black"),
           xlab = "Time (days)", legend.title = "", 
           legend.labs = c("Black", "White"),
           # palette = c("grey27", "grey77"),
           pval = TRUE,
           conf.int = FALSE,
           xlim = c(0, 8000),
           # Add risk table
           tables.height = 0.2,
           risk.table.title = "Risk table",
           risk.table = TRUE,
           risk.table.y.text = FALSE,
           risk.table.fontsize = 4,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(14, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(14, "bold", "black"))
)
myplot$plot <- myplot$plot +
  scale_x_continuous(breaks = c(seq(0, 8000, 2000)))
myplot
```


```{r summarize mean}
markers_ROIi <- ROI_global %>% 
  filter(intratumoral_i_vs_peripheral_p_ == "Intratumoral") %>% 
  group_by(suid) %>% 
  summarize(
    mean_tumor = mean(percent_tumor),
    mean_stroma = mean(percent_stroma),
    mean_total = mean(percent_total),
    # variance_tumor = var(percent_tumor),
    # variance_stroma = var(percent_stroma),
    percent_CD3_tumor = mean(tumor_percent_cd3_opal_650_positive_cells),
    percent_CD8_tumor = mean(tumor_percent_cd8_opal_570_positive_cells),
    percent_CD3_CD8_tumor = mean(tumor_percent_cd3plus_cd8plus_positive_cells),
    percent_FoxP3_tumor = mean(tumor_percent_foxp3_opal_540_positive_cells),
    percent_CD3_FoxP3_tumor = mean(tumor_percent_cd3plus_foxp3plus_positive_cells),
    percent_CD11b_tumor = mean(tumor_percent_cd11b_opal_620_positive_cells),
    percent_CD15_tumor = mean(tumor_percent_cd15_opal_520_positive_cells),
    percent_CD11b_CD15_tumor = mean(tumor_percent_cd11bplus_cd15plus_positive_cells),
    percent_CD3_stroma = mean(stroma_percent_cd3_opal_650_positive_cells),
    percent_CD8_stroma = mean(stroma_percent_cd8_opal_570_positive_cells),
    percent_CD3_CD8_stroma = mean(stroma_percent_cd3plus_cd8plus_positive_cells),
    percent_FoxP3_stroma = mean(stroma_percent_foxp3_opal_540_positive_cells),
    percent_CD3_FoxP3_stroma = mean(stroma_percent_cd3plus_foxp3plus_positive_cells),
    percent_CD11b_stroma = mean(stroma_percent_cd11b_opal_620_positive_cells),
    percent_CD15_stroma = mean(stroma_percent_cd15_opal_520_positive_cells),
    percent_CD11b_CD15_stroma = mean(stroma_percent_cd11bplus_cd15plus_positive_cells),
    
    percent_CD3_total = mean(percent_cd3_opal_650_positive_cells),
    percent_CD8_total = mean(percent_cd8_opal_570_positive_cells),
    percent_CD3_CD8_total = mean(percent_cd3plus_cd8plus_positive_cells),
    percent_FoxP3_total = mean(percent_foxp3_opal_540_positive_cells),
    percent_CD3_FoxP3_total = mean(percent_cd3plus_foxp3plus_positive_cells),
    percent_CD11b_total = mean(percent_cd11b_opal_620_positive_cells),
    percent_CD15_total = mean(percent_cd15_opal_520_positive_cells),
    percent_CD11b_CD15_total = mean(percent_cd11bplus_cd15plus_positive_cells)
  )
markers_ROIi$tumor_variation <- markers_ROIi$mean_tumor - mean(ROI_global$percent_tumor)
markers_ROIi$stroma_variation <- markers_ROIi$mean_stroma - mean(ROI_global$percent_stroma)
markers_ROIi$total_variation <- markers_ROIi$mean_stroma - mean(ROI_global$percent_stroma)
#
markers_ROIp <- ROI_global %>% 
  filter(!str_detect(suid, paste0(remove_id, collapse = "|")), 
         intratumoral_i_vs_peripheral_p_ == "Peripheral") %>% 
  group_by(suid) %>% 
  summarize(
    mean_tumor = mean(percent_tumor),
    mean_stroma = mean(percent_stroma),
    mean_total = mean(percent_total),
    # variance_tumor = var(percent_tumor),
    # variance_stroma = var(percent_stroma),
    percent_CD3_tumor = mean(tumor_percent_cd3_opal_650_positive_cells),
    percent_CD8_tumor = mean(tumor_percent_cd8_opal_570_positive_cells),
    percent_CD3_CD8_tumor = mean(tumor_percent_cd3plus_cd8plus_positive_cells),
    percent_FoxP3_tumor = mean(tumor_percent_foxp3_opal_540_positive_cells),
    percent_CD3_FoxP3_tumor = mean(tumor_percent_cd3plus_foxp3plus_positive_cells),
    percent_CD11b_tumor = mean(tumor_percent_cd11b_opal_620_positive_cells),
    percent_CD15_tumor = mean(tumor_percent_cd15_opal_520_positive_cells),
    percent_CD11b_CD15_tumor = mean(tumor_percent_cd11bplus_cd15plus_positive_cells),
    percent_CD3_stroma = mean(stroma_percent_cd3_opal_650_positive_cells),
    percent_CD8_stroma = mean(stroma_percent_cd8_opal_570_positive_cells),
    percent_CD3_CD8_stroma = mean(stroma_percent_cd3plus_cd8plus_positive_cells),
    percent_FoxP3_stroma = mean(stroma_percent_foxp3_opal_540_positive_cells),
    percent_CD3_FoxP3_stroma = mean(stroma_percent_cd3plus_foxp3plus_positive_cells),
    percent_CD11b_stroma = mean(stroma_percent_cd11b_opal_620_positive_cells),
    percent_CD15_stroma = mean(stroma_percent_cd15_opal_520_positive_cells),
    percent_CD11b_CD15_stroma = mean(stroma_percent_cd11bplus_cd15plus_positive_cells),
    percent_CD3_total = mean(percent_cd3_opal_650_positive_cells),
    percent_CD8_total = mean(percent_cd8_opal_570_positive_cells),
    percent_CD3_CD8_total = mean(percent_cd3plus_cd8plus_positive_cells),
    percent_FoxP3_total = mean(percent_foxp3_opal_540_positive_cells),
    percent_CD3_FoxP3_total = mean(percent_cd3plus_foxp3plus_positive_cells),
    percent_CD11b_total = mean(percent_cd11b_opal_620_positive_cells),
    percent_CD15_total = mean(percent_cd15_opal_520_positive_cells),
    percent_CD11b_CD15_total = mean(percent_cd11bplus_cd15plus_positive_cells)
  )
markers_ROIp$tumor_variation <- markers_ROIp$mean_tumor - mean(ROI_global$percent_tumor)
markers_ROIp$stroma_variation <- markers_ROIp$mean_stroma - mean(ROI_global$percent_stroma)
markers_ROIp$total_variation <- markers_ROIp$mean_total - mean(ROI_global$percent_total)

# Join Intratumoral and Peropheral ROI
markers_ROI <- full_join(markers_ROIi, markers_ROIp,
                         by= "suid", suffix= c(".i", ".p"))
markers_ROI <- left_join(markers_ROI, clinical_data, by="suid")
# clust_markers <- markers_ROI
```


```{r new median}
markers_ROI <- markers_ROI %>% 
  
  mutate(CD3_tumor.i = case_when(
    
    percent_CD3_tumor.i <= 1      ~ "low",
    percent_CD3_tumor.i > 1       ~ "high"
  ), CD3_tumor.i = factor(CD3_tumor.i, levels = c("low","high"))) %>% 
  mutate(CD3_CD8_tumor.i = case_when(
    percent_CD3_CD8_tumor.i <= 1      ~ "low",
    percent_CD3_CD8_tumor.i > 1       ~ "high"
  ), CD3_CD8_tumor.i = factor(CD3_CD8_tumor.i, levels = c("low","high"))) %>% 
  mutate(CD3_FoxP3_tumor.i = case_when(
    percent_CD3_FoxP3_tumor.i <= 1      ~ "low",
    percent_CD3_FoxP3_tumor.i > 1       ~ "high"
  ), CD3_FoxP3_tumor.i = factor(CD3_FoxP3_tumor.i, levels = c("low","high"))) %>% 
  mutate(CD11b_tumor.i = case_when(
    percent_CD11b_tumor.i == 0      ~ "Absence",
    percent_CD11b_tumor.i > 0       ~ "Presence"
  )) %>% 
  mutate(CD11b_CD15_tumor.i = case_when(
    percent_CD11b_CD15_tumor.i == 0      ~ "Absence",
    percent_CD11b_CD15_tumor.i > 0       ~ "Presence"
  )) %>% 
  
  mutate(CD3_stroma.i = case_when(
    percent_CD3_stroma.i <= 1      ~ "low",
    percent_CD3_stroma.i > 1       ~ "high"
  ), CD3_stroma.i = factor(CD3_stroma.i, levels = c("low","high"))) %>% 
  mutate(CD3_CD8_stroma.i = case_when(
    percent_CD3_CD8_stroma.i <= 1      ~ "low",
    percent_CD3_CD8_stroma.i > 1       ~ "high"
  ), CD3_CD8_stroma.i = factor(CD3_CD8_stroma.i, levels = c("low","high"))) %>% 
  mutate(CD3_FoxP3_stroma.i = case_when(
    percent_CD3_FoxP3_stroma.i <= 1      ~ "low",
    percent_CD3_FoxP3_stroma.i > 1       ~ "high"
  ), CD3_FoxP3_stroma.i = factor(CD3_FoxP3_stroma.i, levels = c("low","high"))) %>% 
  mutate(CD11b_stroma.i = case_when(
    percent_CD11b_stroma.i == 0      ~ "Absence",
    percent_CD11b_stroma.i > 0       ~ "Presence"
  )) %>%
  mutate(CD11b_CD15_stroma.i = case_when(
    percent_CD11b_CD15_stroma.i == 0      ~ "Absence",
    percent_CD11b_CD15_stroma.i > 0       ~ "Presence"
  )) %>% 
  mutate(CD11b_stroma.i3 = case_when(
    percent_CD11b_stroma.i <= 1      ~ "low",
    percent_CD11b_stroma.i > 1       ~ "high"
  ), CD11b_stroma.i3 = factor(CD11b_stroma.i3, levels = c("low","high"))) %>%
  mutate(CD11b_CD15_stroma.i3 = case_when(
    percent_CD11b_CD15_stroma.i <= 1      ~ "low",
    percent_CD11b_CD15_stroma.i > 1       ~ "high"
  ), CD11b_CD15_stroma.i3 = factor(CD11b_CD15_stroma.i3, levels = c("low","high"))) %>% 
  mutate(CD3_total.i = case_when(
    percent_CD3_total.i <= 1      ~ "low",
    percent_CD3_total.i > 1       ~ "high"
  ), CD3_total.i = factor(CD3_total.i, levels = c("low","high"))) %>% 
  mutate(CD3_CD8_total.i = case_when(
    percent_CD3_CD8_total.i <= 1      ~ "low",
    percent_CD3_CD8_total.i > 1       ~ "high"
  ), CD3_CD8_total.i = factor(CD3_CD8_total.i, levels = c("low","high"))) %>% 
  mutate(CD3_FoxP3_total.i = case_when(
    percent_CD3_FoxP3_total.i <= 1      ~ "low",
    percent_CD3_FoxP3_total.i > 1       ~ "high"
  ), CD3_FoxP3_total.i = factor(CD3_FoxP3_total.i, levels = c("low","high"))) %>% 
  mutate(CD11b_total.i = case_when(
    percent_CD11b_total.i == 0      ~ "Absence",
    percent_CD11b_total.i > 0       ~ "Presence"
  )) %>% 
  mutate(CD11b_CD15_total.i = case_when(
    percent_CD11b_CD15_total.i == 0      ~ "Absence",
    percent_CD11b_CD15_total.i > 0       ~ "Presence"
  )) %>% 
  mutate(CD11b_total.i3 = case_when(
    percent_CD11b_total.i <= 1      ~ "low",
    percent_CD11b_total.i > 1       ~ "high"
  ), CD11b_total.i3 = factor(CD11b_total.i3, levels = c("low","high"))) %>% 
  mutate(CD11b_CD15_total.i3 = case_when(
    percent_CD11b_CD15_total.i <= 1      ~ "low",
    percent_CD11b_CD15_total.i > 1       ~ "high"
  ), CD11b_CD15_total.i3 = factor(CD11b_CD15_total.i3, levels = c("low","high"))) %>% 
  
  
  mutate(CD3_tumor.p = case_when(
    percent_CD3_tumor.p <= 1      ~ "low",
    percent_CD3_tumor.p > 1       ~ "high"
  ), CD3_tumor.p = factor(CD3_tumor.p, levels = c("low","high"))) %>% 
  mutate(CD3_CD8_tumor.p = case_when(
    percent_CD3_CD8_tumor.p <= 1      ~ "low",
    percent_CD3_CD8_tumor.p > 1       ~ "high"
  ), CD3_CD8_tumor.p = factor(CD3_CD8_tumor.p, levels = c("low","high"))) %>% 
  mutate(CD3_FoxP3_tumor.p = case_when(
    percent_CD3_FoxP3_tumor.p <= 1      ~ "low",
    percent_CD3_FoxP3_tumor.p > 1       ~ "high"
  ), CD3_FoxP3_tumor.p = factor(CD3_FoxP3_tumor.p, levels = c("low","high"))) %>% 
  mutate(CD11b_tumor.p = case_when(
    percent_CD11b_tumor.p == 0      ~ "Absence",
    percent_CD11b_tumor.p > 0       ~ "Presence"
  )) %>% 
  mutate(CD11b_CD15_tumor.p = case_when(
    percent_CD11b_CD15_tumor.p == 0      ~ "Absence",
    percent_CD11b_CD15_tumor.p > 0       ~ "Presence"
  )) %>% 
  mutate(CD11b_tumor.p3 = case_when(
    percent_CD11b_tumor.p <= 1      ~ "low",
    percent_CD11b_tumor.p > 1         ~ "high"
  ), CD11b_tumor.p3 = factor(CD11b_tumor.p3, levels = c("low","high"))) %>% 
  mutate(CD11b_CD15_tumor.p3 = case_when(
    percent_CD11b_CD15_tumor.p <= 1      ~ "low",
    percent_CD11b_CD15_tumor.p > 1       ~ "high"
  ), CD11b_CD15_tumor.p3 = factor(CD11b_CD15_tumor.p3, levels = c("low","high"))) %>% 
  mutate(CD3_stroma.p = case_when(
    percent_CD3_stroma.p <= 1      ~ "low",
    percent_CD3_stroma.p > 1       ~ "high"
  ), CD3_stroma.p = factor(CD3_stroma.p, levels = c("low","high"))) %>% 
  mutate(CD3_CD8_stroma.p = case_when(
    percent_CD3_CD8_stroma.p <= 1      ~ "low",
    percent_CD3_CD8_stroma.p > 1       ~ "high"
  ), CD3_CD8_stroma.p = factor(CD3_CD8_stroma.p, levels = c("low","high"))) %>% 
  mutate(CD3_FoxP3_stroma.p = case_when(
    percent_CD3_FoxP3_stroma.p <= 1      ~ "low",
    percent_CD3_FoxP3_stroma.p > 1       ~ "high"
  ), CD3_FoxP3_stroma.p = factor(CD3_FoxP3_stroma.p, levels = c("low","high"))) %>% 
  mutate(CD11b_stroma.p = case_when(
    percent_CD11b_stroma.p == 0      ~ "Absence",
    percent_CD11b_stroma.p > 0       ~ "Presence"
  )) %>% 
  mutate(CD11b_CD15_stroma.p = case_when(
    percent_CD11b_CD15_stroma.p == 0      ~ "Absence",
    percent_CD11b_CD15_stroma.p > 0       ~ "Presence"
  )) %>% 
    mutate(CD11b_stroma.p3 = case_when(
    percent_CD11b_stroma.p <= 1      ~ "low",
    percent_CD11b_stroma.p > 1       ~ "high"
  ), CD11b_stroma.p3 = factor(CD11b_stroma.p3, levels = c("low","high"))) %>% 
  mutate(CD11b_CD15_stroma.p3 = case_when(
    percent_CD11b_CD15_stroma.p <= 1      ~ "low",
    percent_CD11b_CD15_stroma.p > 1       ~ "high"
  ), CD11b_CD15_stroma.p3 = factor(CD11b_CD15_stroma.p3, levels = c("low","high"))) %>% 
  mutate(CD3_total.p = case_when(
    percent_CD3_total.p <= 1      ~ "low",
    percent_CD3_total.p > 1       ~ "high"
  ), CD3_total.p = factor(CD3_total.p, levels = c("low","high"))) %>% 
  mutate(CD3_CD8_total.p = case_when(
    percent_CD3_CD8_total.p <= 1      ~ "low",
    percent_CD3_CD8_total.p > 1       ~ "high"
  ), CD3_CD8_total.p = factor(CD3_CD8_total.p, levels = c("low","high"))) %>% 
  mutate(CD3_FoxP3_total.p = case_when(
    percent_CD3_FoxP3_total.p <= 1      ~ "low",
    percent_CD3_FoxP3_total.p > 1       ~ "high"
  ), CD3_FoxP3_total.p = factor(CD3_FoxP3_total.p, levels = c("low","high"))) %>% 
  mutate(CD11b_total.p = case_when(
    percent_CD11b_total.p == 0      ~ "Absence",
    percent_CD11b_total.p > 0       ~ "Presence"
  )) %>% 
  mutate(CD11b_CD15_total.p = case_when(
    percent_CD11b_CD15_total.p == 0      ~ "Absence",
    percent_CD11b_CD15_total.p > 0       ~ "Presence"
  )) %>% 
  mutate(CD11b_total.p3 = case_when(
    percent_CD11b_total.p <= 1      ~ "low",
    percent_CD11b_total.p > 1       ~ "high"
  ), CD11b_total.p3 = factor(CD11b_total.p3, levels = c("low","high"))) %>% 
  mutate(CD11b_CD15_total.p3 = case_when(
    percent_CD11b_CD15_total.p <= 1      ~ "low",
    percent_CD11b_CD15_total.p > 1       ~ "high"
  ), CD11b_CD15_total.p3 = factor(CD11b_CD15_total.p3, levels = c("low","high"))) 
```

```{r immunoscore per patients mean}
markers_ROI <- markers_ROI %>% 
  mutate(percentile_score_CD3_i = ntile(percent_CD3_total.i, 100) ) %>% 
  mutate(percentile_score_CD3_p = ntile(percent_CD3_total.p, 100) ) %>% 
  mutate(percentile_score_CD8_i = ntile(percent_CD8_total.i, 100) ) %>% 
  mutate(percentile_score_CD8_p = ntile(percent_CD8_total.p, 100) ) 

markers_ROI <- markers_ROI %>%
  mutate(percentile_score_mean = rowMeans( markers_ROI[c("percentile_score_CD3_i", "percentile_score_CD3_p", 
                                                    "percentile_score_CD8_i", "percentile_score_CD8_p")] ))
markers_ROI <- markers_ROI %>%
  mutate(immunoscore_patients = case_when(
    percentile_score_mean <= 10        ~ 0,
    percentile_score_mean <= 25        ~ 1,
    percentile_score_mean <= 70        ~ 2,
    percentile_score_mean <= 95        ~ 3,
    percentile_score_mean > 95         ~ 4 
  )) %>% 
  mutate(immunoscore_patients = factor(immunoscore_patients)) %>% 
  mutate(immunoscore_2018lancet_patients = case_when(
    percentile_score_mean <= 25        ~ "Low",
    percentile_score_mean <= 70        ~ "Intermediate",
    percentile_score_mean > 70         ~ "High"
    )) %>% 
  mutate(immunoscore_2018lancet_patients = factor(immunoscore_2018lancet_patients, levels = c("Low", "Intermediate", "High"))) 
```

```{r clustering}
# set.seed(1234)
# 
# ### Cluster for stroma/tumor in the intratumoral/peritumoral ROIs 
# clust_markers <- markers_ROI %>% 
#   filter(!is.na(markers_ROI$percent_CD3_CD8_tumor.i) & !is.na(markers_ROI$percent_CD3_CD8_tumor.p)) %>% 
#   select(suid, c("percent_CD3_tumor.i", "percent_CD3_CD8_tumor.i", "percent_CD3_FoxP3_tumor.i", "percent_CD11b_tumor.i", "percent_CD11b_CD15_tumor.i",
#                  "percent_CD3_stroma.i", "percent_CD3_CD8_stroma.i", "percent_CD3_FoxP3_stroma.i", "percent_CD11b_stroma.i", "percent_CD11b_CD15_stroma.i",
#                  "percent_CD3_tumor.p", "percent_CD3_CD8_tumor.p", "percent_CD3_FoxP3_tumor.p", "percent_CD11b_tumor.p", "percent_CD11b_CD15_tumor.p",
#                  "percent_CD3_stroma.p", "percent_CD3_CD8_stroma.p", "percent_CD3_FoxP3_stroma.p", "percent_CD11b_stroma.p", "percent_CD11b_CD15_stroma.p"
#                  ))
# 
# clust <- Mclust(scale(clust_markers[,c(2:ncol(clust_markers))]))
# summary(clust)
# 
# X <- clust_markers[,-1]
# BIC <- mclustBIC(X)
# plot(BIC)
# summary(BIC)
# 
# clust_markers$clusters_all_IandP <- clust$classification
# # clust_markers$clusters_all_IandP <- factor(clust_markers$clusters_all_IandP,
# #                                            levels = c(1, 2, 3),
# #                                            labels = c("mid", "high", "low"))
# clust_markers$clusters_all_IandP <- factor(clust_markers$clusters_all_IandP,
#                                            levels = c(1, 2, 3, 4, 5),
#                                            labels = c("mid", "high", "mid-high", "mid-low", "low"))
# clust_markers <- clust_markers %>% mutate(clusters_all_IandP = factor(clusters_all_IandP, levels = c("low", "mid-low", "mid", "mid-high", "high")))
# clust_markers <- clust_markers %>% mutate(clusters_all_IandP = factor(clusters_all_IandP, levels = c("low", "mid", "high")))

# clust_markers %>% 
# tidyr::gather(key = "markers_cat", value = "value",
#               c("percent_CD3_tumor.i":"percent_CD11b_CD15_stroma.i")) %>% 
#   select(suid, clusters_all_IandP, markers_cat, value) %>% 
#   ggplot(aes(x=suid, y=value, group=markers_cat,  color=markers_cat))+
#   geom_boxplot()+
#   facet_grid(.~ clusters_all_IandP)
# clust_markers %>% 
# tidyr::gather(key = "markers_cat", value = "value",
#               c("percent_CD3_tumor.p":"percent_CD11b_CD15_stroma.p")) %>% 
#   select(suid, clusters_all_IandP, markers_cat, value) %>% 
#   ggplot(aes(x=suid, y=value, group=markers_cat,  color=markers_cat))+
#   geom_boxplot()+
#   facet_grid(.~ clusters_all_IandP)
# markers_ROI <- full_join(markers_ROI, clust_markers %>% select(suid, clusters_all_IandP), by = "suid")
# 
# 
# ### Cluster for tumor intratumoral all double positive "percent_CD3_CD8_tumor.i", "percent_CD3_FoxP3_tumor.i", "percent_CD11b_CD15_tumor.i"
# clust_markers <- markers_ROI %>% filter(!is.na(markers_ROI$percent_CD3_CD8_tumor.i ))
# clust <- 
#   Mclust(clust_markers[,c("percent_CD3_CD8_tumor.i", "percent_CD3_FoxP3_tumor.i", "percent_CD11b_CD15_tumor.i")])
# summary(clust)
# clust_markers$dbl_pos <- clust$classification
# clust_markers$dbl_pos <- factor(clust_markers$dbl_pos,
#                                            levels = c(1, 2, 3),
#                                            labels = c("low", "high", "mid"))
# clust_markers <- clust_markers %>% mutate(dbl_pos = factor(dbl_pos, levels = c("low", "mid", "high")))
# 
# ### Cluster for tumor intratumoral CD3-CD8
# clust <- Mclust(clust_markers$percent_CD3_CD8_tumor.i)
# summary(clust)
# clust_markers$clusters_CD3CD8 <- clust$classification
# clust_markers$clusters_CD3CD8 <- factor(clust_markers$clusters_CD3CD8,
#                                            levels = c(1, 2, 3, 4, 5),
#                                            labels = c("low", "mid-low", "mid", "mid-high", "high"))
# 
# ### Cluster for tumor intratumoral CD3-FoxP3
# clust <- Mclust(clust_markers$percent_CD3_FoxP3_tumor.i)
# summary(clust)
# clust_markers$clusters_CD3FoxP3 <- clust$classification
# clust_markers$clusters_CD3FoxP3 <- factor(clust_markers$clusters_CD3FoxP3,
#                                            levels = c(1, 2, 3),
#                                            labels = c("low", "mid", "high"))
# 
# ### Cluster for tumor intratumoral FoxP3 because it can be expressed by tumor cell
# clust <- Mclust(clust_markers$percent_FoxP3_tumor.i)
# summary(clust)
# clust_markers$clusters_FoxP3_ <- clust$classification
# clust_markers$clusters_FoxP3_ <- factor(clust_markers$clusters_FoxP3_,
#                                            levels = c(1, 2, 3, 4),
#                                            labels = c("low", "mid", "mid-high", "high"))
# 
# ### Cluster for tumor intratumoral CD11b/CD15 
# clust <- Mclust(clust_markers$percent_CD11b_CD15_tumor.i)
# summary(clust)
# clust_markers$clusters_CD11bCD15 <- clust$classification
# clust_markers$clusters_CD11bCD15 <- factor(clust_markers$clusters_CD11bCD15,
#                                            levels = c(1, 7, 8),
#                                            labels = c("low", "high", "mid"))
# clust_markers <- clust_markers %>% mutate(clusters_CD11bCD15 = factor(clusters_CD11bCD15, levels = c("low", "mid", "high")))
# 
# markers_ROI <- full_join(markers_ROI, clust_markers %>% select(suid, dbl_pos, clusters_CD3CD8, clusters_CD3FoxP3, clusters_FoxP3_, clusters_CD11bCD15), by = "suid")
# 
# # write_rds(markers_ROI, "markers_ROI.rds")
```
<br>

```{r create group per sample on ROI_global}
ROI_global <- ROI_global %>% 
  
  mutate(CD3_tumor = case_when(
    
    tumor_percent_cd3_opal_650_positive_cells <= 1      ~ "low",
    tumor_percent_cd3_opal_650_positive_cells > 1       ~ "high"
  ), CD3_tumor = factor(CD3_tumor, levels = c("low","high"))) %>% 
  mutate(CD3_CD8_tumor = case_when(
    tumor_percent_cd3plus_cd8plus_positive_cells <= 1      ~ "low",
    tumor_percent_cd3plus_cd8plus_positive_cells > 1       ~ "high"
  ), CD3_CD8_tumor = factor(CD3_CD8_tumor, levels = c("low","high"))) %>% 
  mutate(CD3_FoxP3_tumor = case_when(
    tumor_percent_cd3plus_foxp3plus_positive_cells <= 1      ~ "low",
    tumor_percent_cd3plus_foxp3plus_positive_cells > 1       ~ "high"
  ), CD3_FoxP3_tumor = factor(CD3_FoxP3_tumor, levels = c("low","high"))) %>% 
  mutate(CD11b_tumor = case_when(
    tumor_percent_cd11b_opal_620_positive_cells == 0      ~ "Absence",
    tumor_percent_cd11b_opal_620_positive_cells > 0       ~ "Presence"
  )) %>% 
  mutate(CD11b_CD15_tumor = case_when(
    tumor_percent_cd15_opal_520_positive_cells == 0      ~ "Absence",
    tumor_percent_cd15_opal_520_positive_cells > 0       ~ "Presence"
  )) %>% 
  
  mutate(CD3_stroma = case_when(
    stroma_percent_cd3_opal_650_positive_cells <= 1      ~ "low",
    stroma_percent_cd3_opal_650_positive_cells > 1       ~ "high"
  ), CD3_stroma = factor(CD3_stroma, levels = c("low","high"))) %>% 
  mutate(CD3_CD8_stroma = case_when(
    stroma_percent_cd3plus_cd8plus_positive_cells <= 1      ~ "low",
    stroma_percent_cd3plus_cd8plus_positive_cells > 1       ~ "high"
  ), CD3_CD8_stroma = factor(CD3_CD8_stroma, levels = c("low","high"))) %>% 
  mutate(CD3_FoxP3_stroma = case_when(
    stroma_percent_cd3plus_foxp3plus_positive_cells <= 1      ~ "low",
    stroma_percent_cd3plus_foxp3plus_positive_cells > 1       ~ "high"
  ), CD3_FoxP3_stroma = factor(CD3_FoxP3_stroma, levels = c("low","high"))) %>% 
  mutate(CD11b_stroma = case_when(
    stroma_percent_cd11b_opal_620_positive_cells == 0      ~ "Absence",
    stroma_percent_cd11b_opal_620_positive_cells > 0       ~ "Presence"
  )) %>%
  mutate(CD11b_CD15_stroma = case_when(
    stroma_percent_cd11bplus_cd15plus_positive_cells == 0      ~ "Absence",
    stroma_percent_cd11bplus_cd15plus_positive_cells > 0       ~ "Presence"
  )) %>% 
  
  mutate(CD3_total = case_when(
    percent_cd3_opal_650_positive_cells <= 1      ~ "low",
    percent_cd3_opal_650_positive_cells > 1       ~ "high"
  ), CD3_total = factor(CD3_total, levels = c("low","high"))) %>% 
  mutate(CD3_CD8_total = case_when(
    percent_cd3plus_cd8plus_positive_cells <= 1      ~ "low",
    percent_cd3plus_cd8plus_positive_cells > 1       ~ "high"
  ), CD3_CD8_total = factor(CD3_CD8_total, levels = c("low","high"))) %>% 
  mutate(CD3_FoxP3_total = case_when(
    percent_cd3plus_foxp3plus_positive_cells <= 1      ~ "low",
    percent_cd3plus_foxp3plus_positive_cells > 1       ~ "high"
  ), CD3_FoxP3_total = factor(CD3_FoxP3_total, levels = c("low","high"))) %>% 
  mutate(CD11b_total = case_when(
    percent_cd11b_opal_620_positive_cells == 0      ~ "Absence",
    percent_cd11b_opal_620_positive_cells > 0       ~ "Presence"
  )) %>% 
  mutate(CD11b_CD15_total = case_when(
    percent_cd11bplus_cd15plus_positive_cells == 0      ~ "Absence",
    percent_cd11bplus_cd15plus_positive_cells > 0       ~ "Presence"
  )) 

```

HR Race
```{r}
a <- markers_ROI %>% 
  mutate(race = factor(race, levels = c("White", "Black")))

coxph(Surv(time = a$timeint_fu, 
                   event = a$surv_vital) ~ race + stage + refage, cluster = suid, data =  a)  %>% 
  tbl_regression(exponentiate = TRUE) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
```

***

# RESPONSE survival association in black women by study
## In AACES
```{r}
markers_ROIclust_o <- ROI_global %>%
    # filter(!str_detect(suid, remove_id_bmi)) %>% 
  filter(intratumoral_i_vs_peripheral_p_ == "Intratumoral" & race == "Black" & site == "AAS") %>% 
  rename(CD3 = CD3_total, CD3_CD8 = CD3_CD8_total,
         CD3_FoxP3 = CD3_FoxP3_total, 
         CD11b = CD11b_total, CD11b_CD15 = CD11b_CD15_total)
  
tbl1 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD3 + stage + refage, cluster = suid, data =  markers_ROIclust_o)  %>% 
  tbl_regression(exponentiate = TRUE,
                 include = CD3) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl2 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD3_CD8 + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
  tbl_regression(exponentiate = TRUE,
                 include = CD3_CD8) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
# tbl3 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
#                    event = markers_ROIclust_o$surv_vital) ~ CD3_FoxP3 + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
#   tbl_regression(exponentiate = TRUE,
#                  include = CD3_FoxP3) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl4 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD11b + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
  tbl_regression(exponentiate = TRUE,
                 include = CD11b) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl5 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD11b_CD15 + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
  tbl_regression(exponentiate = TRUE,
                 include = CD11b_CD15) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")

tbl10 <- tbl_stack(list(tbl1, tbl2, tbl4, tbl5))

markers_ROIclust_o <- ROI_global %>% 
    # filter(!str_detect(suid, remove_id_bmi)) %>% 
  filter(!str_detect(suid, paste0(remove_id, collapse = "|")), 
         intratumoral_i_vs_peripheral_p_ == "Peripheral", race == "Black" & site == "AAS") %>% 
  rename(CD3 = CD3_total, CD3_CD8 = CD3_CD8_total,
         CD3_FoxP3 = CD3_FoxP3_total, 
         CD11b = CD11b_total, CD11b_CD15 = CD11b_CD15_total)
  
tbl1 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD3 + stage + refage, cluster = suid, data =  markers_ROIclust_o)  %>% 
  tbl_regression(exponentiate = TRUE,
                 include = CD3) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl2 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD3_CD8 + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
  tbl_regression(exponentiate = TRUE,
                 include = CD3_CD8) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
# tbl3 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
#                    event = markers_ROIclust_o$surv_vital) ~ CD3_FoxP3 + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
#   tbl_regression(exponentiate = TRUE,
#                  include = CD3_FoxP3) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl4 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD11b + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
  tbl_regression(exponentiate = TRUE,
                 include = CD11b) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl5 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD11b_CD15 + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
  tbl_regression(exponentiate = TRUE,
                 include = CD11b_CD15) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")

tbl13 <- tbl_stack(list(tbl1, tbl2, tbl4, tbl5))

tbl_stack(list(tbl10, tbl13), group_header = c("Intratumoral", "Peripheral")) %>% as_gt()
```

## In NCOCS
```{r}
markers_ROIclust_o <- ROI_global %>%
    # filter(!str_detect(suid, remove_id_bmi)) %>% 
  filter(intratumoral_i_vs_peripheral_p_ == "Intratumoral" & race == "Black" & site == "NCO") %>% 
  rename(CD3 = CD3_total, CD3_CD8 = CD3_CD8_total,
         CD3_FoxP3 = CD3_FoxP3_total, 
         CD11b = CD11b_total, CD11b_CD15 = CD11b_CD15_total)
  
tbl1 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD3 + stage + refage, cluster = suid, data =  markers_ROIclust_o)  %>% 
  tbl_regression(exponentiate = TRUE,
                 include = CD3) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl2 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD3_CD8 + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
  tbl_regression(exponentiate = TRUE,
                 include = CD3_CD8) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
# tbl3 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
#                    event = markers_ROIclust_o$surv_vital) ~ CD3_FoxP3 + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
#   tbl_regression(exponentiate = TRUE,
#                  include = CD3_FoxP3) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl4 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD11b + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
  tbl_regression(exponentiate = TRUE,
                 include = CD11b) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl5 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD11b_CD15 + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
  tbl_regression(exponentiate = TRUE,
                 include = CD11b_CD15) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")

tbl10 <- tbl_stack(list(tbl1, tbl2, tbl4, tbl5))

markers_ROIclust_o <- ROI_global %>% 
    # filter(!str_detect(suid, remove_id_bmi)) %>% 
  filter(!str_detect(suid, paste0(remove_id, collapse = "|")), 
         intratumoral_i_vs_peripheral_p_ == "Peripheral", race == "Black" & site == "NCO") %>% 
  rename(CD3 = CD3_total, CD3_CD8 = CD3_CD8_total,
         CD3_FoxP3 = CD3_FoxP3_total, 
         CD11b = CD11b_total, CD11b_CD15 = CD11b_CD15_total)
  
tbl1 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD3 + stage + refage, cluster = suid, data =  markers_ROIclust_o)  %>% 
  tbl_regression(exponentiate = TRUE,
                 include = CD3) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl2 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD3_CD8 + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
  tbl_regression(exponentiate = TRUE,
                 include = CD3_CD8) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
# tbl3 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
#                    event = markers_ROIclust_o$surv_vital) ~ CD3_FoxP3 + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
#   tbl_regression(exponentiate = TRUE,
#                  include = CD3_FoxP3) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl4 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD11b + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
  tbl_regression(exponentiate = TRUE,
                 include = CD11b) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl5 <- coxph(Surv(time = markers_ROIclust_o$timeint_fu, 
                   event = markers_ROIclust_o$surv_vital) ~ CD11b_CD15 + stage + refage, cluster = suid, data =  markers_ROIclust_o) %>%
  tbl_regression(exponentiate = TRUE,
                 include = CD11b_CD15) %>% bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")

tbl13 <- tbl_stack(list(tbl1, tbl2, tbl4, tbl5))

tbl_stack(list(tbl10, tbl13), group_header = c("Intratumoral", "Peripheral")) %>% as_gt()
```

***

